package thebob.assetloader.map.helpers;

public enum  ScheduleAction {
    SCHEDULE_ACTION_NONE,
    SCHEDULE_ACTION_LOCKDOOR,
    SCHEDULE_ACTION_UNLOCKDOOR,
    SCHEDULE_ACTION_OPENDOOR,
    SCHEDULE_ACTION_CLOSEDOOR,
    SCHEDULE_ACTION_GRIDNO,
    SCHEDULE_ACTION_LEAVESECTOR,
    SCHEDULE_ACTION_ENTERSECTOR,
    SCHEDULE_ACTION_STAYINSECTOR,
    SCHEDULE_ACTION_SLEEP,
    SCHEDULE_ACTION_WAKE,
    NUM_SCHEDULE_ACTIONS
}
